_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  DEVICE: "cuda"
  WEIGHTS: "/home/asd/Mission/GaoFen/bridge_new/baselines/ResNet/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.3
    NUM_CLASSES: 1
  PIXEL_MEAN: [102, 101, 94.6]
  PIXEL_STD: [1.0, 1.0, 1.0]
INPUT:
  FORMAT: "BGR"
  MIN_SIZE_TRAIN: (640, 1000)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1001
  MIN_SIZE_TEST: 0
  MAX_SIZE_TEST: 0 # Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 640), max_size=1001, sample_style='choice')]
  # CROP:
  #   ENABLED: True
  #   TYPE: "relative_range"
  #   SIZE: [0.8, 0.8]
DATASETS:
  TRAIN: ("bridge_dataset_train",)
  TEST: ("laji_test", )
  #"208_test",)
SOLVER:
  MAX_ITER: 80000  # 17.4 epochs
  BASE_LR: 0.002
  GAMMA: 0.1
  STEPS: (60000,)

  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 500
  WARMUP_METHOD: "linear"

  CHECKPOINT_PERIOD: 2000 # 保存间隔
  IMS_PER_BATCH: 4
TEST:
  EVAL_PERIOD: 1000 #每1000个迭代评估验证集一次
  DETECTIONS_PER_IMAGE: 50
  AUG:
    ENABLED: False
    MIN_SIZES: (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
    MAX_SIZE: 4000
    FLIP: True
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 20
OUTPUT_DIR: '/home/asd/Project/BridgeDetection/Faster-RCNN-Trainer/output'
  